### ISSUE TITLE
Possible Issues with Compiling for Bambino 210e

### ISSUE THREAD

**Issue by kasandell** [adamgreen/gcc4mbed#56]
I'd like to preface this by saying Arthur Wolf sent me here to open this issue. I've been trying to get the Smoothie2 source to run on the bambino 210e for about the past 2-3 weeks with no luck. The first sign of an issue is when making gcc4mbed, the compilation of the sample programs fail with the error 
`No rule to make target "../../external/mbed/libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_8_0_0/s110_nrf51822_8.0.0_softdevice.hex"`. 
However, I can still use BuildShell after the failed compilation. 
I'm not sure how much this has to do with gcc4mbed but when following your instructions in Smoothie2Notes on how to flash over USB bootloader, the only available memory is SPIFI, so there is no bank A or B available to flash. After flashing the code to SPIFI through lpcscrypt, there is no communication between my computer and the board. This made me think that something in either gcc4mbed or Smoothie2 might not be right for executing from SPIFI. I do know, however, that the board is functioning and able to run code properly from SPIFI, because I have loaded sample programs from dfusec onto the board, and they have run. I also know that my usb ports are not malfunctioning because I've hooked up my old Azteeg x5 mini and it communicates fine.
The only reason I can think of that this is happening is that the gcc4mbed support for the lpc4330(bambino processor) is possibly only good for the lpc4337(smoothie2 board). 

Many thanks in advance for any help. 

P.S. I forgot to mention I'm running all of this on my mac air running OSX 10.11. I have also tried the ISP loading technique from your notes, but it failed to load code onto the bambino.

**Comment by adamgreen** [comment]
First of all this bug should be moved to the Smoothie2 tree. It is specific to the code/makefiles there.

You can probably ignore the missing softdevice.hex error.

I think you are hitting two issues:
* Smoothie2 makefile is setup to build for the actual Smoothie2 board.
* My lpcscrypt instructions are for the Smoothie2 board as well.

Once the issue is tracked over in the correct project, we can try to work out a solution over there for you and your hardware.
