### ISSUE TITLE
Update to Mbed-OS

### ISSUE THREAD

**Issue by Testato** [adamgreen/gcc4mbed#57]
will this project updated to mbed-os ?
https://github.com/ARMmbed/mbed-os

**Comment by adamgreen** [comment]
I have plans to try and switch to it in the future but it might not be until the new year. I will keep this issue open until that time. Thanks, Adam.

**Comment by adamgreen** [comment]
I recently pushed up changes to the master branch which adds support for mbed-os-5.4.5/release 142.
