### ISSUE TITLE
make deploy issue

### ISSUE THREAD

**Issue by wuliuxiansheng** [adamgreen/gcc4mbed#67]
I am trying this offline compiler on a NUCLEO_F303K8 board and I can compile the code to generate the binary file but when I run `make NUCLEO_F303K8-deploy`, I just receive `make: Nothing to be done for 'NUCLEO_F303K8-deploy'.`. How does `make deploy` work? Can I use the DEVICE variable in Makefile to do `make deploy`?

**Comment by adamgreen** [comment]
You can checkout https://github.com/adamgreen/gcc4mbed/blob/master/notes/install.creole#deploy for more information on how the environment variable should be setup to enable the deploy rules.
