### ISSUE TITLE
gcc4mbed raspbian stretch (ROS kinetic)

### ISSUE THREAD

**Issue by calm0815** [adamgreen/gcc4mbed#70]
Dear Adam,

I'm trying to set up the gcc4mbed compiler on raspbian stretch (ROS kinetic) .
But, linux_install cannot do its task. So, what can I do next ?

linux_install.log says
`
1Sun Sep 23 17:11:08 JST 2018 Starting ./linux_install
 2Sun Sep 23 17:11:08 JST 2018 Executing wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/6_1-2017q1/gcc-arm-none-eabi-6-2017-q1-update-linux.tar.bz2
 3Sun Sep 23 17:14:36 JST 2018 Validating md5 signature of GNU Tools for ARM Embedded Processors
 4Sun Sep 23 17:14:38 JST 2018 Executing tar xf /home/pi/adamgreen-gcc4mbed-7d79ef3/gcc-arm-none-eabi-6-2017-q1-update-linux.tar.bz2
 5Sun Sep 23 17:19:04 JST 2018 Executing mv /home/pi/adamgreen-gcc4mbed-7d79ef3/gcc-arm-none-eabi-6-2017-q1-update /home/pi/adamgreen-gcc4mbed-7d79ef3/gcc-arm-none-eabi
 6Sun Sep 23 17:19:04 JST 2018 Executing make -C samples/ clean-all LPC1768
 7make: Entering directory '/home/pi/adamgreen-gcc4mbed-7d79ef3/samples'
 8Cleaning HelloWorld/KL25Z
 9Cleaning HelloWorld/K64F
10Cleaning HelloWorld/LPC1768
11Cleaning HelloWorld/NRF51_DK
12Cleaning ../../external/mbed-os/Debug
13Cleaning ../../external/mbed-os/Develop
14Cleaning ../../external/mbed-os/Release
15Cleaning Blink/LPC1768
16Cleaning ../../external/mbed-os/Debug
17Cleaning ../../external/mbed-os/Develop
18Cleaning ../../external/mbed-os/Release
19Cleaning Ticker/KL25Z
20Cleaning Ticker/K64F
21Cleaning Ticker/LPC1768
22Cleaning Ticker/NRF51_DK
23Cleaning ../../external/mbed-os/Debug
24Cleaning ../../external/mbed-os/Develop
25Cleaning ../../external/mbed-os/Release
26Cleaning StdIO/KL25Z
27Cleaning StdIO/K64F
28Cleaning StdIO/LPC1768
29Cleaning StdIO/NRF51_DK
30Cleaning ../../external/mbed-os/Debug
31Cleaning ../../external/mbed-os/Develop
32Cleaning ../../external/mbed-os/Release
33Cleaning SdPerf/K64F
34Cleaning SdPerf/LPC1768
35Cleaning ../../external/mbed-os/Debug
36Cleaning ../../external/mbed-os/Develop
37Cleaning ../../external/mbed-os/Release
38Cleaning TCPSocket_HelloWorld/K64F
39Cleaning TCPSocket_HelloWorld/LPC1768
40Cleaning ../../external/mbed-os/Debug
41Cleaning ../../external/mbed-os/Develop
42Cleaning ../../external/mbed-os/Release
43Cleaning USBMouse/KL25Z
44Cleaning USBMouse/K64F
45Cleaning USBMouse/LPC1768
46Cleaning ../../external/mbed-os/features/unsupported/USBDevice/Debug
47Cleaning ../../external/mbed-os/features/unsupported/USBDevice/Develop
48Cleaning ../../external/mbed-os/features/unsupported/USBDevice/Release
49Cleaning ../../external/mbed-os/Debug
50Cleaning ../../external/mbed-os/Develop
51Cleaning ../../external/mbed-os/Release
52Cleaning BLEHeartRate/NRF51_DK
53Cleaning ../../external/mbed-os/Debug
54Cleaning ../../external/mbed-os/Develop
55Cleaning ../../external/mbed-os/Release
56make[1]: Entering directory '/home/pi/adamgreen-gcc4mbed-7d79ef3/samples/HelloWorld'
57Preprocessing ../../external/mbed-os/targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_ARM/LPC1768.ld
58../../build/device-common.mk:201: recipe for target 'LPC1768/HelloWorld.ld' failed
59make[1]: Leaving directory '/home/pi/adamgreen-gcc4mbed-7d79ef3/samples/HelloWorld'
60Makefile:82: recipe for target 'HelloWorld.LPC1768' failed
61make: Leaving directory '/home/pi/adamgreen-gcc4mbed-7d79ef3/samples'
62../../gcc-arm-none-eabi/bin/arm-none-eabi-gcc: 1: ../../gcc-arm-none-eabi/bin/arm-none-eabi-gcc: ^?ELF^B^A^A^B: not found
63../../gcc-arm-none-eabi/bin/arm-none-eabi-gcc: 2: ../../gcc-arm-none-eabi/bin/arm-none-eabi-gcc: Syntax error: "(" unexpected
64make[1]: *** [LPC1768/HelloWorld.ld] Error 2
65make: *** [HelloWorld.LPC1768] Error 2
66Sun Sep 23 17:22:10 JST 2018 Failure forced early exit`

Thanks in advance.

**Comment by adamgreen** [comment]
The gcc4mbed install scripts just work for x86 desktop versions of Windows, macOS, and Linux. They don't work on ARM based development machines. Before these scripts existed, [these manual installation steps](https://github.com/adamgreen/gcc4mbed/blob/master/notes/install.creole#installation) documented how people should set their host machine up to build for mbed targets. You might want to start with those instruction instead, substituting an appropriate way to get the arm-none-eabi-gcc installed on your device.
