### ISSUE TITLE
Inclusion of FEATURE_LWIP

### ISSUE THREAD

**Issue by mateusmenezes95** [adamgreen/gcc4mbed#72]
Dear Adam!

https://github.com/adamgreen/gcc4mbed/blob/7d79ef307e65f4f913bed655c887a632352c286c/build/ARCH_MAX-device.mk#L11
Should not FEATURE_LWIP be included here?

When I try to compile the code without FEATURE_LWIP for the ARCH_MAX target, I get an error in not including the [EthernetInterface.h](https://github.com/adamgreen/gcc4mbed/blob/master/external/mbed-os/features/FEATURE_LWIP/lwip-interface/EthernetInterface.h). However, when I include FEATURE_LWIP in the `ARCH_MAX-device.mk` file, the code compiles without errors

Error message:
```
...src/main.cpp:7:10: fatal error: EthernetInterface.h: No such file or directory
...#include <EthernetInterface.h>
```

**Comment by mateusmenezes95** [comment]
Sorry, I was wrong!

**Comment by adamgreen** [comment]
This project is no longer under active development.
